name: Run latex

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "latex"
    latex:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4

            # Install minimal TeX Live and required packages
            - name: Install minimal TeX Live and required packages
              run: |
                  sudo apt-get update
                  sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended latexmk tex-gyre texlive-fonts-extra texlive-science

            # Finally run make latex
            - name: Create PDF and clean up
              run: |
                  make latex

            # Upload compiled PDF as an artifact
            - name: Upload PDF
              uses: actions/upload-artifact@v4
              with:
                  name: compiled-pdf
                  path: report/main.pdf
